name: Test Workflow

on:
  push:
    branches-ignore:
      - ci
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun run ci

      - name: Test
        run: bun run test

      - name: Build
        run: bun run build
